name: NodeJS with Webpack

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Build
      uses: actions/checkout@v2
      with:
        host: ${{ secrets.HCAI_HOST }}
        username: ${{ secrets.HCAI_USERNAME }}
        key: ${{ secrets.HCAI_PRIVATE_KEY }}
        port: ${{ secrets.HCAI_PORT }}
        script: 'cd /home/ubuntu/hcais/HCAIs-Surveillance-Backend && ./deploy.sh'
